language: emacs-lisp
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > evm-travis.sh && source ./evm-travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
script:
  ./run-travis-ci.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e0a71227d62f6fbba877
