language: emacs-lisp
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > evm-travis.sh && source ./evm-travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-25.1-travis
script:
  ./run-travis-ci.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e0a71227d62f6fbba877
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
