(require 'paredit)
(require 'clj-refactor)

(describe "completable-for-cljr-slash?"
  (expect (not (completable-for-cljr-slash? nil)))
  (dolist (prefix '("" "^" "^::"))
    (expect (completable-for-cljr-slash? (concat prefix "a")))
    (expect (completable-for-cljr-slash? (concat prefix "a-")))
    (expect (completable-for-cljr-slash? (concat prefix "a2")))
    (expect (completable-for-cljr-slash? (concat prefix "a-2")))
    (expect (completable-for-cljr-slash? (concat prefix "a2-")))
    (expect (completable-for-cljr-slash? (concat prefix "a2.a")))
    (expect (completable-for-cljr-slash? (concat prefix "a2.a-")))
    (expect (completable-for-cljr-slash? (concat prefix "a2.a2")))
    (expect (completable-for-cljr-slash? (concat prefix "a2.a-2")))
    (expect (completable-for-cljr-slash? (concat prefix "a2.a2-")))
    (expect (not (completable-for-cljr-slash? (concat prefix "a2.a."))))
    (expect (not (completable-for-cljr-slash? (concat prefix "a2.2"))))
    (expect (not (completable-for-cljr-slash? (concat prefix "a2.2a"))))
    (expect (not (completable-for-cljr-slash? (concat prefix "a2.-"))))
    (expect (not (completable-for-cljr-slash? (concat prefix "a2.-a"))))
    (expect (not (completable-for-cljr-slash? (concat prefix "-"))))
    (expect (not (completable-for-cljr-slash? (concat prefix "."))))
    (expect (not (completable-for-cljr-slash? (concat prefix "2"))))
    (expect (not (completable-for-cljr-slash? (concat prefix "+"))))
    (expect (not (completable-for-cljr-slash? (concat prefix "+"))))
    (expect (not (completable-for-cljr-slash? (concat prefix "a/"))))
    (expect (not (completable-for-cljr-slash? (concat prefix "a/a"))))
    (expect (not (completable-for-cljr-slash? (concat prefix "a/a/"))))))
