Feature: Interactive refactoring

  Background:
    Given I have a project "cljr" in "tmp"
    And I have a clojure-file "tmp/src/cljr/core.clj"
    And I open file "tmp/src/cljr/core.clj"
    And I clear the buffer

  Scenario: Show all actions on pressing "?"
    Given I am in buffer "core.clj"
    When I press "C-! ?"
    Then I should be in buffer "*cljr-key: dispatch*"
    Then I should see message "Run 'actions' with their prefixes. '?' for more help."
    Then I should see "Actions"
    Then I should see "a: Add"
    Then I should see "c: Cycle"
    Then I should see "d: Destructure keys"
    Then I should see "e: Expand let"
    Then I should see "i: Introduce Let"
    Then I should see "m: Move"
    Then I should see "n: Sort ns declaration"
    Then I should see "r: Rename/Replace"
    Then I should see "s: Stop referring"
    Then I should see "t: Thread"
    Then I should see "u: Unwind"
    When I press "q"

  Scenario: Quit actions buffer on pressing "q"
    Given I am in buffer "core.clj"
    When I press "C-! ?"
    When I press "q"
    Then I should be in buffer "core.clj"
    Then the buffer should be empty

  Scenario: Show describe-function help on pressing "?" and any prefix key
    Given I am in buffer "core.clj"
    When I press "C-! ? ? i"
    Then I should be in buffer "*cljr-key: dispatch*"
    When I press "C-x o"
    Then I should be in buffer "*Help*"
    When I press "C-x o"
    When I press "q"

  Scenario: Quit describe-function help on pressing "q"
    Given I am in buffer "core.clj"
    When I press "C-! ? ? i"
    Then I should be in buffer "*cljr-key: dispatch*"
    When I press "q"
    Then I should be in buffer "core.clj"
    Then the buffer should be empty

  Scenario: Show add actions on pressing "?" and "a"
    Given I am in buffer "core.clj"
    When I press "C-! ?"
    When I press "a"
    Then I should be in buffer "*cljr-key: add*"
    Then I should see "d: Add declaration"
    Then I should see "i: Add :import to ns"
    Then I should see "r: Add :require to ns"
    Then I should see "u: Add :use to ns"
    When I press "q"

  Scenario: Show cycle actions on pressing "?" and "c"
    Given I am in buffer "core.clj"
    When I press "C-! ?"
    When I press "c"
    Then I should be in buffer "*cljr-key: cycle*"
    Then I should see "c: Cycle collection"
    Then I should see "p: Cycle definition privacy"
    Then I should see "s: Cycle string/symbol"
    When I press "q"

  Scenario: Show move actions on pressing "?" and "m"
    Given I am in buffer "core.clj"
    When I press "C-! ?"
    When I press "m"
    Then I should be in buffer "*cljr-key: move*"
    Then I should see "f: Move form to file"
    Then I should see "l: Move to let"
    When I press "q"

  Scenario: Show rename and replace actions on pressing "?" and "r"
    Given I am in buffer "core.clj"
    When I press "C-! ?"
    When I press "r"
    Then I should be in buffer "*cljr-key: rename*"
    Then I should see "f: Rename file and ns"
    Then I should see "u: Replace :use with :refer :all"
    When I press "q"

  Scenario: Show thread actions on pressing "?" and "t"
    Given I am in buffer "core.clj"
    When I press "C-! ?"
    When I press "t"
    Then I should be in buffer "*cljr-key: thread*"
    Then I should see "f: Thread with ->"
    Then I should see "l: Thread with ->>"
    Then I should see "h: Thread expression"
    When I press "q"

  Scenario: Show unwind actions on pressing "?" and "u"
    Given I am in buffer "core.clj"
    When I press "C-! ?"
    When I press "u"
    Then I should be in buffer "*cljr-key: unwind*"
    Then I should see "a: Fully unwind threaded expression"
    Then I should see "w: Unwind threaded expression"
    When I press "q"
