name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Emacs ${{ matrix.emacs-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs-version: ['28.2', '29.4', '30.1', 'snapshot']
        include:
          - os: macos-latest
            emacs-version: '30.1'
          - os: windows-latest
            emacs-version: '30.1'
    continue-on-error: ${{ matrix.emacs-version == 'snapshot' }}

    steps:
      - uses: actions/checkout@v5

      - uses: jcs090218/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: emacs-eldev/setup-eldev@v1

      - run: eldev -dtT -p test
        name: Test

      - run: eldev lint
        name: Lint
        if: matrix.emacs-version == '30.1' && matrix.os == 'ubuntu-latest'

      - run: eldev -dtT compile --warnings-as-errors
        name: Compile
